name = "Aeon's Cobblemon Pack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2beef3299fa57f5c6f1e3a883be5ae197dbe1e5725f1f3804f1274de64d8a09f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"

[options]
datapack-folder = "global_packs/required_data"
