name = "Aeon's Cobblemon Pack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b08624a695836b5ebbb53ee0732426a95d4bdcdb76312e7e7ab65cb5b08d093a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"

[options]
datapack-folder = "global_packs/required_data"
