name = "Aeon's Cobblemon Pack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90f4e4aa0086fa7abc6b3a09e8dcd69da51eef7b8057f93849a59d7b2e32b76b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"

[options]
datapack-folder = "global_packs/required_data"
