name = "Aeon's Cobblemon Pack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc263d16d74b2bf9cb50d82aa26005868c67ffa9b8291ae41e002ed180f6adca"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"

[options]
datapack-folder = "global_packs/required_data"
