name = "Eternal Industry"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a30da28aa5cb05b8e0983f2bc57f4572889ec835fd9cb4b7fd3e4b0922150c45"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.82"
