name = "Eternal Industry"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bd1b6c4f183dc4794ff3bac19558d646804e63709deecf4614d68a9743a1fbd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.82"
