name = "Eternal Industry"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f7c15638f7f79117c88c52d25b73b2f9f6dbf9b97d539f55c0fbfbae72b7496"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.82"
