name = "Eternal Industry"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e02704143428191f0a87cc9604c549718dd7a413f26846f57100bd3938176ea7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.82"
