name = "Eternal Industry"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38ed4a0c92050ed5fb38bb041e744da5943ac7078b7a4aa8305f1bd459071942"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.82"
