name = "Eternal Industry"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "333c91199861cb2ec739649232409266438e0f92e5ffffca3df842d2302dad6c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.82"
