name = "Eternal Industry"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "512f8c032390a667083bd9653a86d59c9cf91c4ac3a0896408fdd44bf60bdfab"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.82"
