name = "Ancient's Industria"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be6fdcf3bd92e39ae9d114fdf286c5541d87d0bd8b3d9579c32ca283b97fe032"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
unsup = "1.0.2"
