name = "Ancient's Industria"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1cede2b226e8294da53be2d0e3f637c0b2711a36efb523d4dc4edbba423b5db"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
unsup = "1.0.2"
