name = "Ancient's Industria"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8f6658060d3bf4250d62f6eaff85b809ca362305aea896fe01f84f61a8c9ce5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
unsup = "1.0.2"
