name = "Ancient's Industria"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8bec8db900131436ee613d90d744bd51452fa9675b98cf5ee6ec553303b8d97"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
