name = "Ancient's Industria"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abc020e05b5c4a5d1757a46665c88cb6f69c95d6bafc81a6a4fa3dc4c6f7c2a4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
