name = "Ancient's Industria"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "890324fd1664d90b52f6fc57573b7981a25a2b30d9bf2e90a8096984af01141d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
unsup = "1.0.2"
