name = "Ancient's Industria"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31a09b7095e87822876eb049f847a88320690554b49c6fb77161bd6f56b7a240"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.133"
unsup = "1.0.2"
