[flavor_groups.rendering]
name = "Rendering Mod"
description = "Rendering mod to use. Sodium is better and more effective, however it has some layer sorting issues that result in Wings wings having no visable feathers and looking like grotesque fleshy appendages instead of wings. Embeddium does not have this issue."
side = "both"
[[flavor_groups.rendering.choices]]
id = "rendering_sodium"
name = "Sodium"
description = "Installs Sodium."
[[flavor_groups.rendering.choices]]
id = "rendering_embeddium"
name = "Embeddium"
description = "Installs Embeddium."
[[flavor_groups.rendering.choices]]
id = "rendering_none"
name = "No"
description = "Do not install a rendering mod."

[flavor_groups.ears]
name = "Ears"
description = "Uses the otherwise-blank space on a modern 64x64 skin in combination with alpha layer encoding to give extra features to your player model, such as ears, wings, a custom cape, breasts, a snout and more. Client only. No effect (other than seeing other players Ears skins) if you do not have an Ears skin. Client only."
side = "client"
[[flavor_groups.ears.choices]]
id = "ears_on"
name = "Yes"
description = "Installs Ears."
[[flavor_groups.ears.choices]]
id = "ears_off"
name = "No"
description = "Do not install Ears."

[flavor_groups.yeetus]
name = "Yeetus Experimentus"
description = "Removes the experimental settings warning on creating a new world. Client only."
side = "client"
[[flavor_groups.yeetus.choices]]
id = "yeetus_on"
name = "Yes"
description = "Installs Yeetus Experimentus."
[[flavor_groups.yeetus.choices]]
id = "yeetus_off"
name = "No"
description = "Do not install Yeetus Experimentus."

[flavor_groups.invessentials]
name = "Inventory Essentials"
description = "Adds minimal, consistent inventory features. Ctrl-click stack to move single item, shift-ctrl-click item to move all stacks of that item, shift-drag to move items. Client with additional server functionality."
side = "both"
[[flavor_groups.invessentials.choices]]
id = "invessentials_on"
name = "Yes"
description = "Installs Inventory Essentials."
[[flavor_groups.invessentials.choices]]
id = "invessentials_off"
name = "No"
description = "Do not install Inventory Essentials."

[flavor_groups.mousetweaks]
name = "Mouse Tweaks"
description = "It's Mouse Tweaks. Either you know what it does, or you're living under a rock."
side = "both"
[[flavor_groups.mousetweaks.choices]]
id = "mousetweaks_on"
name = "Yes"
description = "Installs Mouse Tweaks."
[[flavor_groups.mousetweaks.choices]]
id = "mousetweaks_off"
name = "No"
description = "Do not install Mouse Tweaks."

[flavor_groups.invsorter]
name = "Inventory Sorter"
description = "Simple inventory sorting and scroll item movement. Middle click sorts, mousewheel in and out of inventory one item at a time. Both required for functionality, but optional on client."
side = "both"
[[flavor_groups.invsorter.choices]]
id = "invsorter_on"
name = "Yes"
description = "Installs Inventory Sorter."
[[flavor_groups.invsorter.choices]]
id = "invsorter_off"
name = "No"
description = "Do not install Inventory Sorter."


[metafile.sodium]
flavors = "rendering_sodium"
[metafile.embeddium]
flavors = "rendering_embeddium"
[metafile.ears]
flavors = "ears_on"
[metafile.yeetusexperimentus]
flavors = "yeetus_on"
[metafile.inventory-essentials]
flavors = "invessentials_on"
[metafile.mouse-tweaks]
flavors = "mousetweaks_on"
[metafile.inventory-sorter]
flavors = "invsorter_on"