name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbee98d47e54491f8b858a6ce85aeacbf8f9f34d08fd22e353e95a4450063602"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
