name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d448d3687f2967ff41f039371dc18e5021588f32ab5b2bbf8cfb6d002edd743"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
