name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e06ec04ab339649d1a64ad3632a1c2dd674cf9d0bad72fc411be652dc3dac3f"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
