name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6cead766e8ac929fa55bc0c8790c85c3cd73e521c1004dd465015f92d47b8b35"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
