name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6df79cc4087e5f8deb43af64c55235454fc3e7bb0a0b30b2a0c4e396924205e9"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
