name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16476498f851262c06aa2fcd9fcca767e62f6065f21b3f54acf0a278c6c9e0a5"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
