name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0452b6bc8f46e63ac91146ddabc0f38dc531119d7d3a3c0dcdc98e3c83f33d0"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
