name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2b113f35ffe73b41f7172073fb584df2d6aa0356f4c5f9ce9c859e5ad83b462"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
