name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5495092fce2e8229d3299fee3969c329016a4b2bb80ee305768e15b48a169a20"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
