name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f185f287b5dc170d30b61e38a2ce0282b43572fe6e68fde360427bde608a80a8"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
