name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29d62363223ef0c1af31894db406a05da8b08c5ac8e1cbca34f8c26adfdb09f2"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
