name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b77eba82d1bab9c7e47f4e432c661adc5d363f8859989677c40d1b7de906e035"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
