name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59bc2a2b6908604cdc0ac9690f7dbb847eacb9888e0da66d79243c47bb2362f1"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
