name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bda01fee1e4187b8227e1e293890f11f92736a277a06d25d4550e57347e63c5f"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
