name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01a04ca480de09f82af1352320ccbb31077177dd8e9a45125ff00972bacabffa"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
