name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d5877f14e68a23eb4ab945ae69c8f69ed8df6371ca7528a79cd60af2620cd1f"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
