name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c0994c8efa8957a66eea9dc89fe102224f4af69b788a76725f3ac2e924fa1d3"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
