name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07ca9cc5bb807002220ac099c5c92fe5a2929fc055ac3929d80357f09eaccffd"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
