name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d70b5291010255a80324ac4c60dd155dd5b4237d7ae10d73bbd2f5f15af03547"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
