name = "Thaumstrostity"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37addd05e453dbbdf3168494a53306e9d03d9c94d42f892a4d66bbc3091bd972"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
