name = "Thaumstrostity"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be4189826f2e4564bf4aeea62336a90840a2f3e3d47f004d3cffe29955a2d40f"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
