name = "Thaumstrostity"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d85f07cb95e88730aade17916b667f46a50289ab816ecc9ecd379009e9b750f2"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
