name = "Thaumstrostity"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "795bfeeae3e27dd0ad2b2e3aee23c47eacd4cd2ee89d49cf31b869a205e93d1a"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
