name = "Fabrick"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c64074450490dbfb292f90d265cc7c3f17e27f4ad6274893d6055aede7a6b79a"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
