name = "Fabrick"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9511964eb9d37285c50b5c0572c916115c422b65297422ad1a7387afcfa66ff"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
