name = "Fabrick"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36cb89f97cfe1fc29797ddf32ddfe4fb182293847e95b9d0cd28ac0d1221d064"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
