name = "Fabrick"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d16accf0570a3706a79acc356e58ddbb10fdfadc816afc199fc436b72d24f63"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
