name = "Fabrick"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fce325f02afca034ba5548b9c35455e592211d6d2fa22c9a234d81b75655bc5"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
