name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae01591fa808a923d89467f4ed2eaa56380683800a0ec7559c251bb2d2fab7c1"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
