name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1e6a6ac07b79a3a2165917535fdcc49addd07601392b0e9c3db8d44458ada02"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
