name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d08221d800fc8f7daf9bf30a9d089884cfa70b4954749044f3ee8401c3a48908"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
