name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe82f2fb1f46d56726fc8aa5a683df4280b70eec1d7137dadae9e21464330f7f"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
