name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "770934c75783e094a1ab8a30489c1cb18f00b40325e521c712b1b67e51c13e9c"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
