name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ab824491f2c28a2e7e12ac26290f869a440f3205e6746574868b3e61faf3ee4"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
