name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7754a488d7d6dac65852d9dbc8f91a52f66f7373fc4e98cea8523866d48427f9"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
