name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "931162d111a6489fc97f500dac65ad7cda145ffa411c17cad4d05a9a95c9401d"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
