name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1df08b5f8ff339bb067978c74a3fc69969b4edad630dcadc7ba5c0bd87c02a7d"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
