name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0285b5918df86932255eeabb57e8a7614bdd154e050a9f9fa3f409f1e9af8e0d"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
