name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40f845c2f89e592afb1539df49e444fced9fa1d992077b0e93492a7825e6b918"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
