name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "191c3f852f7f9baf22cf1120642ab067f43db9c93dd4126ecd1fc92dee06893d"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
