name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d61b246d84d32227a071695c83b4c7ee133fb266c1d99dc812c24d4579cd31be"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
