name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4ebd9466a7b0579c86bfee0fab147ac5d9305a03134e11e52ab53074c9649d7"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
