name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b7e063be4e4eb79c95b9fc89c72f83aa7310a4782ed98b713e9a331ac51127b"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
