name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f56a783a1fd4438b23d9c8d92f07bde9b4648ffd52ac08ccbd8463167d2db6a7"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
