name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b92eee9726f5d1821b3dd83aadb7b1b783b7ea79fb40eebace849fa60104ebc"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
