name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4eb8b0be4404077e92cb58b1b1adc88140244a23ed595cb6f36ecb6d9c1c2c25"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
