name = "Chromaticrack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ca423fb81a9546095e0fa850fb30f0d889acfbd40f789a7cc7fb29028a0ec7b"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
