name = "Eternal Industry"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d03fa538661b293475bea8977a243d98a83e2ac21fd45acbd9aff97b5ce9e7b4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.82"
