name = "Eternal Industry"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64e13ab9bfcf849d0622194ba50584cfeb5e022770dac5214b815db08c0c700b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.82"
