name = "Eternal Industry"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5cd4ceb10adc5cab40d8c6badb21944c3966093525de93e3616b9d67bf9d58c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.82"
