name = "Eternal Industry"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b432d620add89417a3934628fd1b9fc8ccb5479205eac4235a60951b2fee866"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.82"
