name = "Eternal Industry"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a9d35df14d16d1e7ec856562a49023d0da4040a6d0bc90da0e4bfaec6649575"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.82"
