name = "Eternal Industry"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "973c50cebb8ed45cf2aebf0d198ff8b002c06a26a8ad8a144a0a7980c4ff2f85"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.82"
