name = "Eternal Industry"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af7ec9ef686644267081cc556f9b71ea21a7ee546ad93d75debf0ba45e375a6f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.82"
