name = "Eternal Industry"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18e76503042cac6a763de5bc459a6544b9605b3a854d96d51b86df803f3d6853"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.82"
