name = "Thaumstrostity"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c0d21bc6ef8618f4a1b3db0ba9873f0e98209f92f86e607d288bfb706d61d1c"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
