name = "Thaumstrostity"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc5e8be46cd98759768b3a6572aa1e74160926ce1a87c65c59b55ecc48a2b20d"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
