name = "Fabrick"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e14a5d6e023ad6dd052e761b85d38c152217d8b052fb94bad9556be9efae38c0"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
