name = "Fabrick"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f1c9b8c29704dbfaea04c89469fc04fcc0945117baf8ce461057c8b99ed6e18"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
