name = "Fabrick"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6753cd7e31b4a4f344aa792a323bc3c0ddb7435d0b7ce947a58e025c739ca9c9"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
