name = "Fabrick"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b18d554b75edd5bdde3037ed22e517b047584f2455c7ff1c3c65571c88d9259"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
