name = "Fabrick"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9122d10f57a19cc770383e1b26e8399bc04952cf6a9f3399545612f2d579ef9c"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
