name = "Fabrick"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b4ef4126ccb8c8d6746f49f72d0ca86c8dfb256f57b44e30b266af1817e9b54"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
