name = "Fabrick"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a201327f9e0a3678999bf0e7133af24032595aa262a550c459ec6f575b1c21fc"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
