name = "Fabrick"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a1713af91571d01a7d61d48dbc6c40b688ff67dd615e069c3905f87861660a0"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
